---
name: "❓ Support / Preguntas"
about: Obtén ayuda o haz consultas sobre el proyecto
title: "[SUPPORT]:"
labels: question
assignees: ''

---

body:
  - type: markdown
    attributes:
      value: >
        Bienvenido(a). Esta plantilla es para **preguntas** generales, dudas de uso o soporte no relacionado con bugs o nuevas funciones.

  - type: input
    id: question
    attributes:
      label: "Pregunta/Duda principal"
      description: "Explica en una frase la cuestión que tienes."
      placeholder: "Ej.: ¿Cómo actualizar el modpack a la v1.2?"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Detalles"
      description: "Describe a fondo tu pregunta, incl. contexto y lo que intentaste."
      placeholder: "Incluye capturas, pasos realizados, etc."
    validations:
      required: false
